- Name: lootbox1
  Icon: Default
  OpenVFX: fx_Potion_frostresist
  Description: Test your skills
  Lootbox Type: One
  Send Webhook: false
  Item List:
  - Prefab: Wood
    Min: 1
    Max: 100
    Level: 1
    Chance: 100
  - Prefab: SwordIron
    Min: 1
    Max: 1
    Level: 4
    Chance: 100

- Name: lootbox2
  Icon: chest_hildir1
  OpenVFX: none
  Description: Test your skills
  Lootbox Type: All
  Send Webhook: false
  Item List:
  - Prefab: Wood
    Min: 1
    Max: 100
    Level: 1
    Chance: 100
  - Prefab: SwordIron
    Min: 1
    Max: 1
    Level: 4
    Chance: 100

- Name: lootbox3
  Icon: chest_hildir2
  OpenVFX: vfx_spawn
  Description: Test your skills
  Lootbox Type: AllWithChance
  Send Webhook: false
  Item List:
  - Prefab: Wood
    Min: 1
    Max: 100
    Level: 1
    Chance: 50
  - Prefab: SwordIron
    Min: 1
    Max: 1
    Level: 4
    Chance: 20
    
- Name: lootbox4
  Icon: chest_hildir3
  OpenVFX: sfx_spawn
  Description: Test your skills
  Lootbox Type: AllWithChanceShowTooltip
  Send Webhook: false
  Item List:
  - Prefab: Wood
    Min: 1
    Max: 100
    Level: 1
    Chance: 50
  - Prefab: SwordIron
    Min: 1
    Max: 1
    Level: 4
    Chance: 20